# -*- coding: utf-8 -*-
"""custommath

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Xv5lnBqOUBIvxEinCOiuebVxXwSxspk
"""

#task
def factorial(n):
   if n==1:
    return n
   return n*factorial(n-1)

def fibonacci(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  return fibonacci(n-1)+fibonacci(n-2)
def gcd(a,b):
  if b==0:
    return a
  return gcd(b,a%b)
print(factorial(5))
print(fibonacci(6))
print(gcd(6,4))